Added Category entity with all related dto, service, mapper and controller.
nklimovych/book-store pull request #12
Opened 2024-05-15 14:37 UTC by nklimovych

2024-05-16 10:32 UTC, vikkushnir approved these changes
LGTM! Only few minor comments

2024-05-16 10:32 UTC, vikkushnir commented on src/main/resources/db/changelog/changes/08-create-category-table.yaml
> +                    nullable: false
```suggestion
                    nullable: false
                    
```

2024-05-16 10:32 UTC, vikkushnir commented on src/main/java/mate/academy/bookstore/service/impl/CategoryServiceImpl.java
> +    }
```suggestion
@Service
@RequiredArgsConstructor
public class CategoryServiceImpl implements CategoryService {
    private final CategoryRepository categoryRepository;
    private final CategoryMapper categoryMapper;
```

2024-05-16 13:53 UTC, andrii-hoienko requested changes
Nice! left some comments

2024-05-16 13:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/service/CategoryService.java
> +
```suggestion
```

2024-05-16 13:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/service/impl/CategoryServiceImpl.java
> +    }
agree

2024-05-16 13:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/service/impl/CategoryServiceImpl.java
> +        categoryRepository.deleteById(id);
make check before delete as you did in update

2024-05-16 13:53 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/08-create-category-table.yaml
> +                    nullable: false
Not resolved

2024-05-17 10:52 UTC, yevheniisynytsia approved these changes

2024-05-17 10:52 UTC, yevheniisynytsia commented on src/main/java/mate/academy/bookstore/exception/GlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleMethodRepository(DuplicateEntityException ex) {
```suggestion
    protected ResponseEntity<Object> handleDuplicateEntity(DuplicateEntityException ex) {
```

2024-05-17 11:35 UTC, merged