Added Order entity with all related dto, service, mapper and controller
nklimovych/book-store pull request #14
Opened 2024-05-22 21:59 UTC by nklimovych

2024-05-23 13:48 UTC, andrii-hoienko requested changes
Good job! Left some comments

2024-05-23 13:48 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/controller/OrderController.java
> +        return orderService.getOrderItem(orderId, itemId);
You should accept user here as well, Because currently one user will see orderItems of different user (check all endpoints)

2024-05-23 13:48 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/model/order/Order.java
> +    @OneToMany(mappedBy = "order", cascade = CascadeType.REMOVE)
Why only remove? I think you should cascades for save and update

2024-05-23 13:48 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +    }
Should be done in cart service

2024-05-23 13:48 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +    }
What is the reason to make this map? you already have all necessary information in CartItem

2024-05-23 13:48 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +    private Map<Book, Integer> getBooks(ShoppingCart cart) {
Are you sure that equals and hashCode is overridden for Book, you other entities not override this methods

2024-05-23 13:48 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +        orderRepository.save(order);
You save order 2 times in same method

2024-05-23 13:48 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +    public Set<OrderItem> saveOrderItem(Order order, Map<Book, Integer> book) {
```suggestion
    private Set<OrderItem> saveOrderItem(Order order, Map<Book, Integer> book) {
```

2024-05-23 13:48 UTC, andrii-hoienko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/13-create-order-items-table.yaml
```suggestion
      file: db/changelog/changes/13-create-order-items-table.yaml
      
```

2024-05-23 13:48 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/repository/cart/ShoppingCartRepository.java
> +    Optional<ShoppingCart> findByUser_Id(Long userId);
```suggestion
    Optional<ShoppingCart> findByUserId(Long userId); //dont forget about naming convention
```

2024-05-23 13:48 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/model/order/OrderItem.java
> +@Setter
Add equals, hashCode and toString to entites

2024-05-24 13:24 UTC, andrii-hoienko requested changes
Nice, left minor comments

2024-05-24 13:24 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/model/order/OrderItem.java
> +@Setter
Not resolved (please check ALL entities)

2024-05-24 13:24 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +        List<OrderItem> items = itemRepository.findByOrderId(orderId);
I alredy commented about it, please make sure that one user can not access order data of other user

2024-05-24 13:24 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +        if (!order.getUser().equals(user)) {
Did you override equals in User entity?

2024-05-24 13:24 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +                                     "Unable to proceed: Order item not found with id: " + itemId));
Yoy can find order item by orderIt,, orderItemId and userId, and it will take only one db reuqest instead of 2 as implemented now

2024-05-24 13:36 UTC, nklimovych commented on src/main/java/mate/academy/bookstore/model/order/OrderItem.java
> +@Setter
Did not mention that it was a comment directed to all entities. Will be done

2024-05-25 11:35 UTC, d1sam requested changes
Good job, but there are minor changes, that should be done!

2024-05-25 11:35 UTC, d1sam commented on src/main/java/mate/academy/bookstore/model/CartItem.java
> +@ToString
```suggestion
@ToString(exclude = {"shoppingCart", "book"})
```

2024-05-25 11:35 UTC, d1sam commented on src/main/java/mate/academy/bookstore/model/ShoppingCart.java
you should exclude from `@EqualsAndHashCode` and `@ToString` all fields, that contains relations.
please also make this in all of the `@Entry`

2024-05-25 11:35 UTC, d1sam commented on src/main/java/mate/academy/bookstore/model/order/OrderItem.java
> +    private int quantity;
```suggestion
    private Integer quantity;
```
I prefer to use the wrapped type as you can tell if the object has been saved/loaded to/from the database whether or not the id value is null.

2024-05-25 11:35 UTC, d1sam commented on src/main/java/mate/academy/bookstore/model/order/Order.java
> +    private LocalDateTime orderDate;
```suggestion
    @CreationTimestamp
    private LocalDateTime orderDate;
```

2024-05-27 08:26 UTC, karma-o approved these changes
GJ!

2024-05-27 08:34 UTC, merged